name: Play Music on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  play_music:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Play Music
        run: |
          sudo apt-get update
          sudo apt-get install -y mpg123
          mpg123 your-music-file.mp3
